[build-system]
requires = [
  "setuptools >= 61.0",
  "setuptools_scm",
  "cython",
  "numpy",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyembree"
description = "Python wrapper for Intel Embree"
authors = [
    { name="Anthony Scopatz", email="scopatz@gmail.com" },
    { name="Adam Hendry", email="adam.grant.hendry@gmail.com" },
    { name="Meagan Lang", email="langmm.astro@gmail.com" },
]
maintainers = [
    { name="Adam Hendry", email="adam.grant.hendry@gmail.com" },
    { name="Meagan Lang", email="langmm.astro@gmail.com" },
]
dynamic = [
  "version",
  "readme",
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
  "numpy",
]
requires-python = ">=3.10"
license-files = ["LICENSE"]
keywords = [
  "pyembree"
]

[project.urls]
Homepage = "https://github.com/scopatz/pyembree"
Documentation = "https://github.com/scopatz/pyembree"
Repository = "https://github.com/adam-grant-hendry/pyembree"
Issues = "https://github.com/scopatz/pyembree/issues"
Changelog = "https://github.com/scopatz/pyembree/blob/main/CHANGELOG.rst"

[project.optional-dependencies]
dev = [
  # 'pyline>=2.12.2',
  'pytest>=7.0.1',
  'coverage>=6.3.2',
  'ipython>=8.1.1',
  'isort>=5.10.1',
  'black>=22.3.0',
]

[tool.setuptools]
packages = ["pyembree"]
include-package-data = true
package-data = {pyembree = ['*.pxd']}

[tool.setuptools.dynamic]
readme = {file = ["README.rst"]}

[tool.setuptools_scm]
version_file = "pyembree/_version.py"
scm.git.describe_command = "git describe --tags --abbrev=0"

